version: '3'
services:
    openehrtool:
        build: 
          context: .
          dockerfile: ./Dockerfile.prod
        image: surfercrs4/openehrtoolprod
        volumes:
            - .:/code
        network_mode: host                  
        env_file:
            - ./.env.prod
        depends_on:
            - "redis"    

    redis:
        image: redis:alpine
        ports:
        - 6379:6379
        command:  redis-server  /redis.conf
        volumes:
        - ./redis.conf:/redis.conf          